[font]
size = 22.0

[window]
padding = { x = 15, y = 10 }

[font.normal]
family = "JetBrains Mono"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#c5c8c6"
background = "#151515" # 131f21 looks fancy

# Normal colors
[colors.normal]
black   = '#110f18'
red     = '#ff6767'
green   = '#53f855'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

# Bright colors
[colors.bright]
black   = '#4d4d4d'
red     = '#ff6767'
green   = '#85f855'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

[colors.selection]
text       = 'CellForeground'
background = '#29263c'
