width = 1200
height = 500
auto_height = true
font = "{{font_name}}"
font_size = 28
bg_color = "#1e1d2f"
font_color = "#d9e0ee"

[input_text]
prompt_color = "#7aa2f7"
margin = "10"
padding = "5"
prompt  = "Run"

[list_items]
margin = "10"
item_spacing = 10
selected_font_color = "#f28fad"
match_color = 0xe69f66ff
hide_actions = true
show_default = false

[icon]
size = 21
theme = "Adwaita"
