[symlinks]
"fish/config.fish" = "/home/filtsin/.config/fish/config.fish"
"fish/fish_plugins" = "/home/filtsin/.config/fish/fish_plugins"
"fish/fish_variables" = "/home/filtsin/.config/fish/fish_variables"
"hypr/bg.jpg" = "/home/filtsin/.config/hypr/bg.jpg"
"hypr/hyprland.conf" = "/home/filtsin/.config/hypr/hyprland.conf"
"hypr/hyprpaper.conf" = "/home/filtsin/.config/hypr/hyprpaper.conf"
"nvim/init.lua" = "/home/filtsin/.config/nvim/init.lua"
"nvim/lua/configs/cmp.lua" = "/home/filtsin/.config/nvim/lua/configs/cmp.lua"
"nvim/lua/configs/crates.lua" = "/home/filtsin/.config/nvim/lua/configs/crates.lua"
"nvim/lua/configs/flash.lua" = "/home/filtsin/.config/nvim/lua/configs/flash.lua"
"nvim/lua/configs/init.lua" = "/home/filtsin/.config/nvim/lua/configs/init.lua"
"nvim/lua/configs/lsp_client/clang.lua" = "/home/filtsin/.config/nvim/lua/configs/lsp_client/clang.lua"
"nvim/lua/configs/lsp_client/init.lua" = "/home/filtsin/.config/nvim/lua/configs/lsp_client/init.lua"
"nvim/lua/configs/lsp_client/lua.lua" = "/home/filtsin/.config/nvim/lua/configs/lsp_client/lua.lua"
"nvim/lua/configs/lsp_client/python.lua" = "/home/filtsin/.config/nvim/lua/configs/lsp_client/python.lua"
"nvim/lua/configs/lsp_client/rust.lua" = "/home/filtsin/.config/nvim/lua/configs/lsp_client/rust.lua"
"nvim/lua/configs/lspsaga.lua" = "/home/filtsin/.config/nvim/lua/configs/lspsaga.lua"
"nvim/lua/configs/lualine.lua" = "/home/filtsin/.config/nvim/lua/configs/lualine.lua"
"nvim/lua/configs/luasnip.lua" = "/home/filtsin/.config/nvim/lua/configs/luasnip.lua"
"nvim/lua/configs/luatab.lua" = "/home/filtsin/.config/nvim/lua/configs/luatab.lua"
"nvim/lua/configs/mason.lua" = "/home/filtsin/.config/nvim/lua/configs/mason.lua"
"nvim/lua/configs/nightfox.lua" = "/home/filtsin/.config/nvim/lua/configs/nightfox.lua"
"nvim/lua/configs/noice.lua" = "/home/filtsin/.config/nvim/lua/configs/noice.lua"
"nvim/lua/configs/oil.lua" = "/home/filtsin/.config/nvim/lua/configs/oil.lua"
"nvim/lua/configs/telescope.lua" = "/home/filtsin/.config/nvim/lua/configs/telescope.lua"
"nvim/lua/configs/tokyonight.lua" = "/home/filtsin/.config/nvim/lua/configs/tokyonight.lua"
"nvim/lua/configs/treesitter.lua" = "/home/filtsin/.config/nvim/lua/configs/treesitter.lua"
"nvim/lua/nvim.lua" = "/home/filtsin/.config/nvim/lua/nvim.lua"
"nvim/lua/plugins.lua" = "/home/filtsin/.config/nvim/lua/plugins.lua"
"nvim/snippets/lua.lua" = "/home/filtsin/.config/nvim/snippets/lua.lua"
"nvim/snippets/rust.lua" = "/home/filtsin/.config/nvim/snippets/rust.lua"
"waybar/config.json" = "/home/filtsin/.config/waybar/config"
"wezterm.lua" = "/home/filtsin/.wezterm.lua"

[templates]
"waybar/style.css" = "/home/filtsin/.config/waybar/style.css"
"yofi.toml" = "/home/filtsin/.config/yofi/yofi.config"
