[helpers]

[common.variables]
font_name = "JetBrains Mono"

[default]
depends = ["common"]

[default.files]
"yofi.toml" = "~/.config/yofi/yofi.config"
"waybar/config.json" = "~/.config/waybar/config"
"waybar/style.css" = "~/.config/waybar/style.css"
"wezterm.lua" = "~/.wezterm.lua"
"alacritty" = "~/.config/alacritty"
"nvim" = { target = "~/.config/nvim/", type = "symbolic" }
"hypr" = "~/.config/hypr/"
"fish" = "~/.config/fish"
"niri" = "~/.config/niri"


